### ISSUE TITLE
Participant not marked as "finished" after completing survey

### ISSUE THREAD

**Issue by mcalderon1** [DukeCityDigital/mysurveys#156]
@DukeCityDigital Participant is still marked as incomplete with no finished timestamp when they are returned to the mysurveys homepage after completing the study survey. When they finish the survey and are redirected back to mysurveys it should mark them as complete and have a timestamp of when the survey was completed.

**Comment by DukeCityDigital** [comment]
@mcalderon1  thanks Maria - I updated things a bit so that after completing a project, whether a user is logged in or not the code in the 'Return' link from unipark will automatically log the user in and mark that project as completed.  

We do need to adjust the return link in Unipark so that it looks like this:  
https://mysurveys.santafe.edu/dashboard/my-projects/**kmvLTYk7pHdo**
 @olssonresearch  let me know if we can switch the link in Unipark to the above format, we should be able to test it today and check that users are getting credit for finishing

**Comment by DukeCityDigital** [comment]
Hi Maria!  I think this should be all set now.  thanks again for being so descriptive it really helps me!

@mcalderon1
